#ifndef ENGINECOMMON_H_INCLUDED
#define ENGINECOMMON_H_INCLUDED

#define COLOR_TEXTURE_UNIT GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX 0
#define SHADOW_TEXTURE_UNIT GL_TEXTURE1
#define SHADOW_TEXTURE_UNIT_INDEX 1
#define NORMAL_TEXTURE_UNIT GL_TEXTURE2
#define NORMAL_TEXTURE_UNIT_INDEX 2
#define RANDOM_TEXTURE_UNIT GL_TEXTURE3
#define RANDOM_TEXTURE_UNIT_INDEX 3
#define INVALID_UNIFORM_LOCATION 0xFFFFFFFF

#endif // ENGINECOMMON_H_INCLUDED
